### ISSUE TITLE
Datu dublēšanās

### ISSUE THREAD

**Issue by MahStuff** [MeSans/Web-expenses-tracker#10]
Pie categoriju nosaukumu izvades, pirmās divas kategorijas dublējas (Work, Living Costs). Hvz kāpēc tā. 
Nedaudz pamainīju kategoriju tabulas ierakstus datu bāzē, varbūt tāpēc?

**Comment by MahStuff** [comment]
Ok, es sapratu ka kateogriju piesaiste lietotājam šobrīd tiek noteikta pēc expenses tabulas, bet tas nozīmē, ka ja kādai tēriņu kategorijai nav pievienoti actual tēriņi (tātad ieraksti), lietotājam šī kategorija nemaz nepiesaistās/neuzrādās caur to foreach loop, kas mums itkā dabū kategoriju nosaukumus. Which shoudn't be like that.

**Comment by MeSans** [comment]
mmkay, tagad informācija par lietotāja kategorijām ir jaunā tabulā.
Es sataisīju tā ka lietotāja visas kategorijas ir vienkārši masīvā:
#11  
Lietotāja kategorijām gan jābūt users_categorys tabulā.

**Comment by MahStuff** [comment]
Awesome, paldies, šobrīd tad viss ar to kārtībā.
